<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KebabSeeder extends Seeder
{
    public function run(): void
    {
        DB::table("kebabs")->insert([
            [
                "logo" => file_get_contents(public_path("Logo/Stambuł.png")),
                "name" => "Stambuł Kebab",
                "address" => "Chojnowska 21A",
                "coordinates" => json_encode(["lat" => 51.207187, "lng" => 16.156937]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany", "czosnek", "ziołowy"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "11:00-23:00",
                    "tuesday" => "11:00-23:00",
                    "wednesday" => "11:00-23:00",
                    "thursday" => "11:00-23:00",
                    "friday" => "11:00-01:00",
                    "saturday" => "11:00-01:00",
                    "sunday" => "12:00-23:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => false,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["pyszne.pl" => "https://www.pyszne.pl/menu/kebab-stambul-legnica-gwarna"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Rulo.png")),
                "name" => "Rulo Kebab",
                "address" => "Nowy Świat",
                "coordinates" => json_encode(["lat" => 51.205062, "lng" => 16.154562]),
                "sauces" => json_encode(["łagodny", "arabski", "ostry", "mieszany"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane"]),
                "status" => "closed",
                "opening_hours" => json_encode([]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => false,
                "is_chainstore" => false,
                "ordering_options" => json_encode(["na miejscu", "na wynos"]),
                "comments" => json_encode([]),
                "pages" => json_encode([]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Bafra.png")),
                "name" => "Bafra Kebab Złotoryjska",
                "address" => "Złotoryjska 170 ",
                "coordinates" => json_encode(["lat" => 51.192937, "lng" => 16.128937]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "11:00-23:00",
                    "tuesday" => "11:00-23:00",
                    "wednesday" => "11:00-23:00",
                    "thursday" => "11:00-23:00",
                    "friday" => "11:00-01:00",
                    "saturday" => "11:00-01:00",
                    "sunday" => "12:00-23:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => false,
                "is_chainstore" => true,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/bafra-kebab-zlotoryjska/", "pyszne.pl" => "https://www.pyszne.pl/menu/bafra-kebab-zlotoryjska"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Cyrus.png")),
                "name" => "Cyrus Kebab",
                "address" => "Rynek 20 ",
                "coordinates" => json_encode(["lat" => 51.207937, "lng" => 16.161062]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-22:00",
                    "tuesday" => "10:00-22:00",
                    "wednesday" => "10:00-22:00",
                    "thursday" => "10:00-22:00",
                    "friday" => "10:00-00:00",
                    "saturday" => "10:00-00:00",
                    "sunday" => "10:00-22:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => true,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["self" => "https://www.cyrus.pl"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Leo.png")),
                "name" => "Leo Kebab",
                "address" => "Jaworzyńska 4",
                "coordinates" => json_encode(["lat" => 51.204437, "lng" => 16.159937]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel", "kapsalon"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-00:00",
                    "tuesday" => "10:00-00:00",
                    "wednesday" => "10:00-00:00",
                    "thursday" => "10:00-00:00",
                    "friday" => "10:00-00:00",
                    "saturday" => "10:00-00:00",
                    "sunday" => "10:00-00:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => true,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/leo-kebab-legnica-lga/", "pyszne.pl" => "https://www.pyszne.pl/menu/leo-kebab-and-grill"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Zahir.png")),
                "name" => "Zahir Kebab",
                "address" => "Jaworzyńska 8",
                "coordinates" => json_encode(["lat" => 51.204187, "lng" => 16.160187]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany", "czosnkowy", "ketchup", "bbq", "koperkowy"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-23:00",
                    "tuesday" => "10:00-23:00",
                    "wednesday" => "10:00-23:00",
                    "thursday" => "10:00-23:00",
                    "friday" => "10:00-23:00",
                    "saturday" => "10:00-23:00",
                    "sunday" => "10:00-23:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => true,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/zahir-kebab-lga/", "pyszne.pl" => "https://www.pyszne.pl/menu/zahir-kebab-jaworzynska"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Piri.png")),
                "name" => "Piri Piri Kebab",
                "address" => "Szkolna 1",
                "coordinates" => json_encode(["lat" => 51.204187, "lng" => 16.160688]),
                "sauces" => json_encode([
                    "łagodny",
                    "ostry",
                    "mieszany",
                    "miodowo-musztardowy",
                    "sriracha mayo",
                    "czosnkowy",
                    "ziołowy",
                    "salsa verde",
                ]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel", "kapsalon"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "11:00-22:00",
                    "tuesday" => "11:00-22:00",
                    "wednesday" => "11:00-22:00",
                    "thursday" => "11:00-22:00",
                    "friday" => "11:00-23:00",
                    "saturday" => "11:00-23:00",
                    "sunday" => "12:00-22:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => true,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/piri-piri-kebab-legnica-lga/", "pyszne.pl" => "https://www.pyszne.pl/menu/kebab-piri-piri-szkolna"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Dino.png")),
                "name" => "Dino Kebab",
                "address" => "Jaworzyńska 41",
                "coordinates" => json_encode(["lat" => 51.200688, "lng" => 16.159438]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel", "kapsalon"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "tuesday" => "11:00-22:00",
                    "wednesday" => "11:00-22:00",
                    "thursday" => "11:00-22:00",
                    "friday" => "11:00-22:00",
                    "saturday" => "12:00-22:00",
                    "sunday" => "12:00-22:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => false,
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/dino-kebab1-lga/", "pyszne.pl" => "https://www.pyszne.pl/menu/kebab-dino"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Zahir.png")), 
                "name" => "Zahir Kebab",
                "address" => "Kolejowa 3 ",
                "coordinates" => json_encode(["lat" => 51.212312, "lng" => 16.168687]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany", "czosnkowy", "ketchup", "bbq", "koperkowy"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-00:00",
                    "tuesday" => "10:00-00:00",
                    "wednesday" => "10:00-00:00",
                    "thursday" => "10:00-00:00",
                    "friday" => "10:00-02:00",
                    "saturday" => "10:00-02:00",
                    "sunday" => "11:00-00:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => true, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/zahir-kebab-lga/", "pyszne.pl" => "https://www.pyszne.pl/menu/zahir-kebab-legnica-kolejowa"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Lara.png")), 
                "name" => "Lara Doner Kebab",
                "address" => "Wrocławska 13 ",
                "coordinates" => json_encode(["lat" => 51.209563, "lng" => 16.167813]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany", "czosnkowy", "ziołowy"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-22:00",
                    "tuesday" => "10:00-22:00",
                    "wednesday" => "10:00-22:00",
                    "thursday" => "10:00-22:00",
                    "friday" => "10:00-22:00",
                    "saturday" => "10:00-22:00",
                    "sunday" => "10:00-22:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => true, 
                "ordering_options" => json_encode(["na miejscu", "na wynos"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/pl/legnica/lara-doner-kebab-lga/"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Karmnik.png")), 
                "name" => "Karmnik Kebab",
                "address" => "Wrocławska 1",
                "coordinates" => json_encode(["lat" => 51.209688, "lng" => 16.168563]),
                "sauces" => json_encode(["łagodny", "ostry", "mieszany"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane"]),
                "status" => "closed", 
                "opening_hours" => json_encode([]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu", "na wynos"]),
                "comments" => json_encode([]),
                "pages" => json_encode([]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Mix.png")), 
                "name" => "MIX Kebab",
                "address" => "Wrocławska 23a",
                "coordinates" => json_encode(["lat" => 51.209187, "lng" => 16.169313]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "11:00-21:00",
                    "tuesday" => "11:00-21:00",
                    "wednesday" => "11:00-21:00",
                    "thursday" => "11:00-21:00",
                    "friday" => "11:00-21:00",
                    "saturday" => "12:00-21:00",
                    "sunday" => "12:00-21:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["pyszne.pl" => "https://www.pyszne.pl/menu/mix-kebab-legnica"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Hallo.png")), 
                "name" => "Hallo Kebap",
                "address" => "Stefana Czarnieckiego 19c",
                "coordinates" => json_encode(["lat" => 51.211687, "lng" => 16.175187]),
                "sauces" => json_encode(["ostry", "czosnkowy", "jogurtowy", "ketchup"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "wednesday" => "12:00-20:00",
                    "thursday" => "12:00-20:00",
                    "friday" => "12:00-21:00",
                    "saturday" => "12:00-21:00",
                    "sunday" => "12:00-21:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => true, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["pyszne.pl" => "https://www.pyszne.pl/menu/hallo-kebap-legnica"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/HadFood.png")), 
                "name" => "Had Food",
                "address" => "Fabryczna 13 ",
                "coordinates" => json_encode(["lat" => 51.206812, "lng" => 16.178688]),
                "sauces" => json_encode(["ketchup", "czosnkowy", "łagodny", "pikantny"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "12:00-22:00",
                    "tuesday" => "12:00-22:00",
                    "wednesday" => "12:00-22:00",
                    "thursday" => "12:00-22:00",
                    "friday" => "12:00-23:00",
                    "saturday" => "12:00-23:00",
                    "sunday" => "12:00-21:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["pyszne.pl" => "https://www.pyszne.pl/menu/had-food"]), 
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/AmAm.png")), 
                "name" => "Am Am Kebab",
                "address" => "Wrocławska 155",
                "coordinates" => json_encode(["lat" => 51.209563, "lng" => 16.187063]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-20:00",
                    "tuesday" => "10:00-20:00",
                    "wednesday" => "10:00-20:00",
                    "thursday" => "10:00-20:00",
                    "friday" => "10:00-20:00",
                    "saturday" => "10:00-20:00",
                    "sunday" => "11:00-20:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => false,
                "is_premises" => true,
                "is_chainstore" => true, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode([
                    "pyszne.pl" => "https://www.pyszne.pl/menu/am-am-kebab-legnica-wroclawska",
                ]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Bejrut.png")), 
                "name" => "Bejrut Restauracja Libańska",
                "address" => "aleja Piłsudskiego 18",
                "coordinates" => json_encode(["lat" => 51.205188, "lng" => 16.185313]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry", "czosnkowy"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-00:00",
                    "tuesday" => "10:00-00:00",
                    "wednesday" => "10:00-00:00",
                    "thursday" => "10:00-00:00",
                    "friday" => "10:00-02:00",
                    "saturday" => "10:00-02:00",
                    "sunday" => "10:00-00:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => true, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://www.pyszne.pl/menu/bejrut-restauracja-libanska-legnica", "pyszne.pl" => "https://glovoapp.com/pl/pl/legnica/bejrut-restauracja-libanska-lga/"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/King.png")), 
                "name" => "King House Kebab",
                "address" => "aleja Piłsudskiego 38",
                "coordinates" => json_encode(["lat" => 51.204563, "lng" => 16.188562]),
                "sauces" => json_encode(["łagodny", "mieszany", "ostry", "czosnkowy", "ketchup", "bbq"]),
                "meats" => json_encode(["kurczak", "wołowina", "mieszane", "falafel"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "tuesday" => "12:00-21:30",
                    "wednesday" => "12:00-21:30",
                    "thursday" => "12:00-21:30",
                    "friday" => "12:00-22:00",
                    "saturday" => "12:00-22:00",
                    "sunday" => "12:00-21:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => true,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode([
                    "pyszne.pl" => "https://www.pyszne.pl/menu/king-house-kebab-legnica",
                    "glovo" => "https://glovoapp.com/pl/pl/legnica/king-house-kebab-lga/",
                ]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => null,
                "name" => "Kavovarka Kebab Kraft",
                "address" => "Górnicza 10B ",
                "coordinates" => json_encode(["lat" => 51.205562, "lng" => 16.186563]),
                "sauces" => json_encode(["łagodny", "ostry", "czosnkowy"]),
                "meats" => json_encode(["kurczak", "wieprzowina", "kraftowy"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "12:00-21:00",
                    "tuesday" => "12:00-21:00",
                    "wednesday" => "12:00-21:00",
                    "thursday" => "12:00-21:00",
                    "friday" => "12:00-21:00",
                    "saturday" => "12:00-21:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => false,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu", "na wynos", "dostawa"]),
                "comments" => json_encode([]),
                "pages" => json_encode(["glovo" => "https://glovoapp.com/pl/en/legnica/kavovarka-lga/"]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => null, 
                "name" => "Kebab Truck",
                "address" => "Iwaszkiewicza 1",
                "coordinates" => json_encode(["lat" => 51.207937, "lng" => 16.213437]),
                "sauces" => json_encode(["czosnkowy", "ziołowy", "ostry", "turecki"]),
                "meats" => json_encode(["kurczak", "mieszane"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "10:00-19:00",
                    "tuesday" => "10:00-19:00",
                    "wednesday" => "10:00-19:00",
                    "thursday" => "10:00-19:00",
                    "friday" => "10:00-19:00",
                    "saturday" => "10:00-19:00",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => false,
                "is_chainstore" => false,
                "ordering_options" => json_encode(["na miejscu", "na wynos"]),
                "comments" => json_encode([]),
                "pages" => json_encode([]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "logo" => file_get_contents(public_path("Logo/Maxi.png")),
                "name" => "Maxi Kebab",
                "address" => "Carrefour, aleja Piłsudskiego 84",
                "coordinates" => json_encode(["lat" => 51.201062, "lng" => 16.214813]),
                "sauces" => json_encode(["łagodny", "czosnkowy", "miętowy", "ostry", "mieszany", "musztardowy"]),
                "meats" => json_encode(["kurczak", "baran", "mieszane"]),
                "status" => "exists",
                "opening_hours" => json_encode([
                    "monday" => "11:30-20:00",
                    "tuesday" => "11:30-20:00",
                    "wednesday" => "11:30-20:00",
                    "thursday" => "11:30-20:00",
                    "friday" => "11:30-20:00",
                    "saturday" => "11:30-20:00",
                    "sunday" => "zamknięte",
                ]),
                "opening_year" => null,
                "closing_year" => null,
                "is_crafted" => true,
                "is_premises" => false,
                "is_chainstore" => false, 
                "ordering_options" => json_encode(["na miejscu", "na wynos"]),
                "comments" => json_encode([]),
                "pages" => json_encode([]),
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
